language: node_js
node_js:
  - "5.0"
before_script:
  - echo "Installing"
  - npm install
  - cd functions
  - npm install
script:
  - echo "Starting"
  - npm run build
install:
  - echo "Firebase tools"
  - npm install -g firebase-tools
after_success:
  - echo "Deploying"
  - firebase deploy --token $FIREBASE_TOKEN
