language: node_js
node_js:
  - 10
before_script:
  - npm install
script:
  - npm test
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
